monolog:
    handlers:
        # Critical errors only
        slack_errors:
            type:        slack
            token:       'xoxb-1446310373157-2022031153749-mYVlNdTnL5dwYdqF5nK9hx7M'
            channel:     '#rdi-manager-logs'
            bot_name:    'OUCH'
            icon_emoji:  ':ghost:' # 👻
            level:         critical
            include_extra: true
